from __future__ import annotations


TEXT_INPUT_MODALITY = "text"
AUDIO_INPUT_MODALITY = "audio"
ASSUMED_DIRECTED = "ASSUMED_DIRECTED"
ASSUMED_CLOSED = "ASSUMED_CLOSED"
TURN_PHASE_COLLECTING_INPUT = "COLLECTING_INPUT"
INGRESS_ACCEPTED = "ACCEPTED"
INGRESS_COMMITTED = "COMMITTED"
MOCK_AUDIO_ACCEPTANCE_BASIS = "mock_rule:assumed_directed_and_closed"
