from __future__ import annotations

from voice_agent.adapters.lalm_thinker_routing_profiles import (
    get_default_lalm_thinker_routing_profile,
)

_DEFAULT_ROUTING_PROFILE = get_default_lalm_thinker_routing_profile()


LALM_THINKER_ROUTING_OUTPUT_RULES = list(_DEFAULT_ROUTING_PROFILE.output_rules)
LALM_THINKER_AUDIO_ROUTING_OUTPUT_RULES = list(_DEFAULT_ROUTING_PROFILE.audio_output_rules)
LALM_THINKER_EVIDENCE_SCHEMA_INSTRUCTION = _DEFAULT_ROUTING_PROFILE.system_instruction

LALM_THINKER_ROUTING_PROMPT_PROFILE_METADATA = _DEFAULT_ROUTING_PROFILE.to_metadata()
